name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Init gradle wrapper
      run: gradle wrapper
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Run gradle tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
